# Serialken/UserBundle/Resources/config

services:
    sonata.admin.user:
        class: Serialken\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
        arguments:
            - ~
            - Serialken\UserBundle\Entity\User
            - ~
#        calls:
#            - [ setTranslationDomain, [SerialkenUserBundle]]