<?php

namespace Serialken\BugTrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowRepository extends EntityRepository
{
}
